<?xml version="1.0" encoding="utf-8"?><Database Name="employee_management" Class="dbEmployeeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-G7SPG85\SQLEXPRESS;Initial Catalog=employee_management;User ID=sqlserverkevin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="con" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="dept_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dept_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Designation" Member="Designations">
    <Type Name="Designation">
      <Column Name="desg_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="desg_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Emp" Member="Emps">
    <Type Name="Emp">
      <Column Name="eno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="dob" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="designation" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="dept" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="salary" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="cv" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>